parameters:
  - name: env
    type: string
    displayName: Environment (dev, prd)
  - name: servConn
    type: string
    displayName: Connection

jobs:
  - job: Deploy_${{ parameters.env }}_services
    displayName: SnipeIT ${{ parameters.env }} Infra
    pool:
      vmImage: $(vmImageName)
    variables:
      - template: ../vars/variables.yml
        system.debug: true
        parameters:
          env: ${{ parameters.env }}
   
    steps:
      - task: AzureCLI@2
        displayName: Create Resource Group
        inputs:
          azureSubscription: ${{ parameters.servConn }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: az group create --name "$(resourceGroupName)" --location "$(location)"

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploy infrastructure
        inputs:
          azureResourceManagerConnection: ${{ parameters.servConn }}
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          csmFile: "$(templatesDir)/infra.bicep"
          overrideParameters: >
            -SnipeITStorageAccount_name $(SnipeITStorageAccount_name)
            -SnipeITServerFarm_name $(SnipeITServerFarm_name)
            -SnipeITDB_name $(SnipeITDB_name)
            -SnipeITWebsite_name $(SnipeITWebsite_name)
            -mysqllogin $(mysqllogin)
            -mysqlpassword $(mysqlpassword)
            -mysqserverlName $(mysqserverlName)
          deploymentName: "DeployPipelineTemplate"

      - task: AzureCLI@2
        inputs:
          azureSubscription: '<YourAzureSubscription>'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Download the SSL certificate
            wget https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem -O DigiCertGlobalRootCA.crt.pem

            # Install Azure CLI if not already installed
            if ! command -v az &> /dev/null
            then
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            fi

            # Upload the SSL certificate to the Azure Files share
            az storage file upload \
              --account-name <YourStorageAccountName> \
              --account-key <YourStorageAccountKey> \
              --share-name snipeit \
              --source DigiCertGlobalRootCA.crt.pem

