parameters:
  - name: env
    type: string
    displayName: Environment (dev, prd)
  - name: servConn
    type: string
    displayName: Connection

jobs:
  - job: Deploy_${{ parameters.env }}_services
    displayName: SnipeIT ${{ parameters.env }} Infra
    pool:
      vmImage: $(vmImageName)
    variables:
      - template: ../vars/variables.yml
        parameters:
          env: ${{ parameters.env }}
   
    steps:
      - task: AzureCLI@2
        displayName: Create Resource Group
        inputs:
          azureSubscription: ${{ parameters.servConn }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: az group create --name "$(resourceGroupName)" --location "$(location)"

      - task: AzureCLI@2
        displayName: Create mysql flexible-server
        inputs:
          azureSubscription: ${{ parameters.servConn }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az mysql flexible-server create --location $(location) --resource-group $(resourceGroupName) `
            --name $(mysqserverlName) --admin-user $(mysqllogin) --admin-password $(mysqlpassword) --sku-name Standard_B1ms `
            --tier Burstable --public-access 0.0.0.0 --storage-size 30 --tags "project=$(tag)" --version 5.7 ` 
            --storage-auto-grow Enabled --iops 360
      
